# Generated by Django 6.0 on 2025-12-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(choices=[('001', "Ma'am Charisse"), ('002', 'Sir Jude'), ('003', 'Sir Gab'), ('004', "Ma'am Cheryl"), ('005', 'Sir Julius')], max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
